@startuml カレーライス
@startuml 並列処理
title フォークで並列処理
start
:材料を買いに行く;
:鍋を用意する;
fork
:具材を刻む;
:フライパンに油を引き温める;
:玉ねぎを炒める;
:玉ねぎに色がついたらひき肉を入れる;
:トマト、ナス、パプリカ、ニンジンを加え炒める;
:水を加え沸騰させる;
:あくをとり、五分程沸騰させる;
:火をとめ、ルーを溶かし、弱火でかき混ぜながら十分温める;
:トマトを加えひと煮立ちさせる;

fork again
:米を洗う;
:米を炊く;
end fork
:お皿に盛り付ける;
stop
@enduml
@enduml