@startuml 演習3-6
object 社員1{
氏名 = "高橋洋平"
}
object 社員2{
氏名 = "樋口正之"
}
object 資格1{
資格名 = "情報処理安全確保支援士"
}
object 資格2{
資格名 = "LinuC試験Level1"
}
社員1 "1"---"*"資格1 :持つ
社員2 "1"---"*"資格1 :持つ
社員1 "1"---"*"資格2 :持つ

@enduml