@startuml 演習3-7
object 顧客1{
名前 = "高田理恵"
住所 = "岩手県盛岡市中央通"
顧客タイプ = "一般顧客"
}
object 顧客2{
名前 = "高橋洋平"
住所 = "岩手県盛岡市中央通"
顧客タイプ = "重要顧客"
}
object 注文1{
注文日 = 11月21日
注文数 = 1
}
object 注文2{
注文日 = 11月21日
注文数 = 2
}
object 注文3{
注文日 = 12月23日
注文数 = 1
}
object テレビ{
型式 = "V12345"
}
object 冷蔵庫{
型式 = "R8765"
}
顧客2 --- 注文1 :注文
顧客2 --- 注文2 :注文
顧客1 --- 注文3 :注文
注文1 --- 冷蔵庫
注文2 --- テレビ
注文3 --- 冷蔵庫
@enduml