@startuml 演習3-5
skinparam classAttributeIconSize 0
object 宿泊客1{
名前 = "A"
}
object 宿泊客2{
名前 = "B"
}
object UMLホテル予約申請{
客室タイプ = "シングル"
チェックイン日 = 5月3日
宿泊期間 = 2日
宿泊費 = 11000円
キャンペーン開始日 = 4月29日
キャンペーン終了日 = 5月6日
キャンペーン価格 = 9000円
}
object 301号室{
宿泊施設名 = "UMLホテル"
宿泊者 = "Aさん"
宿泊期間 = 2日
価格 = 9000円
}
object 302号室{
宿泊施設名 = "UMLホテル"
宿泊者 = ""
宿泊期間 = 
価格 = 
}
object 303号室{
宿泊施設名 = "UMLホテル"
宿泊者 = "Bさん"
宿泊期間 = 
価格 = 9000円
}
宿泊客1 -- UMLホテル予約申請
宿泊客2 -- UMLホテル予約申請
UMLホテル予約申請 -- 301号室
UMLホテル予約申請 -- 302号室
UMLホテル予約申請 -- 303号室
@enduml