@startuml 診察予約
' left to right direction
[*] --right-->メニュー
state メニュー{
}
state 予約と確認{
}
state あなたの順番{
}
state 今の順番{
}
メニュー -down-> 予約と確認 : 予約と確認へ遷移
予約と確認 -up-> メニュー : メニューへ遷移
予約と確認 -right-> あなたの順番 : 登録ボタンを押す
予約と確認 -right-> あなたの順番 : 確認ボタンを押す
あなたの順番 -up-> メニュー :　メニューへ遷移
メニュー -down-> 今の順番 : 今の順番へ遷移
今の順番 -up-> メニュー : メニューへ遷移
メニュー --right--> [*]
@enduml